import localFont from "next/font/local";
import "./globals.css";
import LayoutRoot from "@/components/layout/LayoutRoot";
import { Footer } from "antd/es/layout/layout";

{
  /* <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..8
00;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Vibur&display=swap" rel="stylesheet"/> */
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Dowload Document</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Vibur&family=Roboto:wght@100;300;400;500;700;800;900&family=ZCOOL+QingKe+HuangYou&family=Montserrat:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-desc font-medium text-lg">
        <div className="">
          <LayoutRoot />
        </div>
        <div className=" top-24 left-0 right-0 w-[100vw]">
          {/* <div className="h-28"></div> */}
          {children}
        </div>
        <Footer className="mt-[80px]">
          <hr className="" />
          <div className="my-5 flex justify-around">
            <p>@2024 All rights reserved</p>
            <div>
              <a href="" className="mx-3">
                Thi thử tiếng anh{" "}
              </a>
              <a href="">Xem thời khóa biểu </a>
            </div>
          </div>
        </Footer>
      </body>
    </html>
  );
}
